// Import the built server artifact generated by the monorepo build step.
// Vercel runs the root `pnpm run build` (configured in vercel.json) which
// produces `artifacts/api-server/dist/index.mjs`. Point to that file
// explicitly so the serverless function uses the bundled ESM output.
import app from '../artifacts/api-server/dist/index.mjs';

export default app;